<?php

use BC\Modules\Books\Widget\Blocks;

/** @noinspection PhpFullyQualifiedNameUsageInspection */

/** @var \BC\Modules\Books\Widget\Chapter $this */
$nav = $this->getNavLinks();
$content = new Blocks($this->getChapter()->getContent())->render();
$extractedNotes = $this->extractNotes($content);
$content = $extractedNotes->content;
$notes = $extractedNotes->notes;
?><?=$content?>
<?php if ($notes) : ?>
    <section class="chapter__refs">
        <?php foreach ($notes as $i => $note) : ?>
            <p id="<?=$note->id?>">
                <a href="#<?=$note->id?>_link">↑</a>
                <sup><?=($i + 1)?></sup> <?=$note->content?>
            </p>
        <?php endforeach; ?>
    </section>
<?php endif; ?>
<nav class="chapter__nav">
    <span class="chapter__nav-cell chapter__nav-cell--prev">
        <?php if ($nav['prev']) : ?>
            <a href="<?=$nav['prev'][0]?>" class="chapter__nav-link chapter__nav-link--prev">
                <?=$this->getSvgContent('images/icons/back-arrow.svg')?>
                <?=$nav['prev'][1]?>
            </a>
        <?php endif; ?>
    </span>
    <span class="chapter__nav-cell chapter__nav-cell--toc">
        <a href="<?=$nav['toc'][0]?>" class="chapter__nav-link chapter__nav-link--toc">
            <?=$this->getSvgContent('images/modules/Books/toc.svg')?>
            <?=$nav['toc'][1]?>
        </a>
    </span>
    <span class="chapter__nav-cell chapter__nav-cell--next">
        <?php if ($nav['next']) : ?>
            <a href="<?=$nav['next'][0]?>" class="chapter__nav-link chapter__nav-link--next">
                <?=$nav['next'][1]?>
                <?=$this->getSvgContent('images/icons/back-arrow.svg')?>
            </a>
        <?php endif; ?>
    </span>
</nav>
