<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */

/** @var \BC\Widget\Page\Cringe\CringeMuseum $this */
?>
<br>
<p class="cringe__warning">Внимание: карантинная зона</p>
<h1>Музей кринжа</h1>
<p class="cringe__subtitle">Здесь покоятся мои ранние творческие потуги, которые слишком стыдно показывать, но жаль
    удалять насовсем. Читай и запускай на свой страх и риск: токсичные миазмы
    экспонатов вызывают передоз испанского стыда в организме и внезапное кровотечение из глаз.</p>

<ul class="cringe__exhibition list--block">
    <li class="cringe__exhibit">
        <span class="cringe__type">TEXT_ANOMALY // 2008</span>
        <h2 class="cringe__title">Марс: Вторжение</h2>
        <p class="cringe__description">Пятнадцатилетний автор поиграл в Doom 3 и решил, что миру не хватает буквальной
            новеллизации олдскульного шутера. Сюжетно это сплав событий игры и старенькой новеллизации Дума из
            девяностых: морпех прибывает на Фобос, там разверзается ад, морпех крошит монстров и ищет способ вернуться
            на Землю.</p>
        <p>Читается как протокол допроса свидетеля: «Я пошел. Я открыл дверь. Я выстрелил». Персонажи такие
            плоские, что их можно под каток кидать — они и не заметят.</p>
        <div class="cringe__status">
            <span class="cringe__status-name">Status:</span> Unreadable
            <span class="cringe__status-name">Cringe level:</span> Maximum
        </div>
        <a href="/static/cringe/mars.zip" class="btn btn-secondary cringe__download">Извлечь .ZIP</a>
    </li>
    <li class="cringe__exhibit">
        <span class="cringe__type">SEQUEL_SYNDROME // 2009</span>
        <h2 class="cringe__title">Девять кругов (Марс: Возвращение)</h2>
        <p class="cringe__description">Рецидив графомании автора, сиквел к первому «Марсу». Герои прилетели на Землю,
            но монстры и тут успели натворить делов. Битва продолжается — на нашей родной планете и не только.</p>
        <p class="cringe__description">История ушла далеко от игр, и «Возвращение» уже не похоже на текстовое
            прохождение шутера. Но болячки подростковых фанфиков никуда не делись: герои общаются так, будто зачитывают
            друг другу инструкцию к микроволновке, а нездоровое внимание автора к мелким деталям порой поражает. Если
            герой моргает — вы узнаете, под каким углом опустились его веки.</p>
        <p class="cringe__description">Написано с душой, но читать это больно.</p>
        <div class="cringe__status">
            <span class="cringe__status-name">Status:</span> Barely readable
            <span class="cringe__status-name">Cringe level:</span> Above normal
        </div>
        <a href="/static/cringe/mars2.zip" class="btn btn-secondary cringe__download">Извлечь .ZIP</a>
    </li>
    <li class="cringe__exhibit">
        <span class="cringe__type">BIOHAZARD_CODE // 2012</span>
        <h2 class="cringe__title">CyberShock</h2>
        <p class="cringe__description">Движок на Delphi для текстового рогалика, написанный во времена, когда у меня
            было слишком много энтузиазма и времени, но маловато понимания основ программирования :) ООП отсутствует
            напрочь (наследие паскаля), нейминг уровня <code>procedure bitva</code> и <code>function pricel</code>,
            лапшекод во всей его постыдной красоте.</p>
        <p class="cringe__description">Антипаттерны архитектуры тут как покемоны — CyberShock собрал их все.</p>
        <div class="cringe__status">
            <span class="cringe__status-name">Status:</span> Лапши больше, чем в самой лапше
            <span class="cringe__status-name">Cringe level:</span> Компилятор удалился от стыда, увидев этот код
        </div>
        <a href="/static/cringe/cybershock.zip" class="btn btn-secondary cringe__download">Извлечь .ZIP</a>
    </li>
</ul>
