<?php

namespace BC\Modules\Blog\Widget;

use BC\Core\Trait\DateConverterTrait;
use BC\Modules\Blog\Model\Post as PostModel;
use BC\Widget\AWidget;
use BC\Widget\Page\APage;
use DateTime;
use Runway\Exception\RuntimeException;

class Post extends AWidget {
    use DateConverterTrait;

    protected ?PostModel $post = null {
        get {
            return $this->post;
        }
    }

    protected ?APage $page = null {
        get {
            return $this->page;
        }
    }

    protected function applyContext(array $context): void {
        parent::applyContext($context);

        if (!$this->post && !(($context['post'] ?? null) instanceof PostModel)) {
            throw new RuntimeException(__METHOD__ . ': post is not set or not an instance of ' . PostModel::class);
        }

        if (($this->context['post'] ?? null) instanceof PostModel) {
            $this->post = $this->context['post'];
        }

        if (($this->context['page'] ?? null) instanceof APage) {
            $this->page = $this->context['page'];
        }
    }

    public function render(array $context = []): string {
        if (!$this->post) {
            throw new RuntimeException(__METHOD__ . ': post is not set');
        }

        if (!$this->page) {
            throw new RuntimeException(__METHOD__ . ': page is not set');
        }

        return parent::render($context); // TODO: Change the autogenerated stub
    }

    protected function getTemplatePath(): string {
        return 'modules/Blog/post.phtml';
    }

    protected function getTitle(): string {
        return $this->post->getTitle();
    }

    protected function getDateTime(DateTime $dt): string {
        return $this->getDateConverter()->toIsoFormat($dt);
    }

    protected function getHumanReadableDateTime(DateTime $dt): string {
        return $this->getDateConverter()->toShortForm(
            $dt->getTimestamp(),
        );
    }
}
