<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */
/** @var \BC\Widget\Page\Home\Pulse $this */
$items = $this->getItems();
?>
<?php if ($items) : ?>
    <h2>Хайлайты</h2>

    <link rel="stylesheet" href="<?=$this->getAssetBuilder()->getBundleWebPath('grid', 'css')?>"/>
    <div class="grid">
        <?php foreach ($items as $item): ?>
            <?=new \BC\Widget\Page\Home\PulseItem(['item' => $item])->render()?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
