<?php

use BC\Widget\Common\Picture;

/** @noinspection PhpFullyQualifiedNameUsageInspection */
/** @var \BC\Modules\Games\Widget\GamesList\GamesListItem $this */
?><?php if ($game = $this->getGame()) : ?>
    <li class="game">
        <article class="game__card">
            <?=new Picture([
                'image'        => $game->game->getCover(),
                'class'        => 'block__image-img',
                'pictureClass' => 'game__card-miniature',
                'lazyLoad'     => true,
                'alt'          => $game->game->getTitle(),
                'retina'       => false,
                'breakpoints'  => [
                    -1 => 200,
                ],
            ])->render()?>
            <header class="game__card-header">
                <h2 class="game__name"><?=$game->game->getTitle()?></h2>
                <?php if ($releaseYear = $game->game->getReleaseYear()) : ?>
                    <span class="game__year"><?=$releaseYear?></span>
                <?php endif; ?>
            </header>
            <ul class="game__materials list--block">
                <?php foreach ($game->getMaterials() as $material) : ?>
                    <li class="game__materials-item">
                        <a href="<?=$material->getMaterialUrl()?>" class="game__material">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                                 viewBox="1 2 12 14" class="game__material-icon">
                                <path
                                    d="M13.014 3.638v11.133a.476.476 0 0 1-.475.475H3.214a1.34 1.34 0 0 1-.813-.333L1.325 13.86a1.3 1.3 0 0 1-.34-.808V3.638a.476.476 0 0 1 .476-.475H12.54a.476.476 0 0 1 .474.475m-2.208.954a.476.476 0 0 0-.475-.475H3.67a.476.476 0 0 0-.475.475v3.212a.476.476 0 0 0 .475.475h6.66a.476.476 0 0 0 .476-.475zm-.5 5.883a.477.477 0 0 0-.475-.476H4.16a.477.477 0 0 0-.475.476v3.442a.476.476 0 0 0 .475.475h5.67a.476.476 0 0 0 .475-.475zm-4.356.635H4.74v2.2h1.21z"></path>
                            </svg>
                            <h3 class="game__material-title"><?=$material->getShortTitle()?></h3>
                            <span class="game__material-description"><?=$material->getAnnotation()?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </article>
    </li>
<?php endif; ?>
