<?php

use BC\Widget\Common\Picture;

/** @noinspection PhpFullyQualifiedNameUsageInspection */
/** @var \BC\Modules\Games\Widget\GamesList\GamesListItem $this */
?><?php if ($game = $this->getGame()) : ?>
    <li class="game">
        <article class="game__card">
            <?=new Picture([
                'image'        => $game->game->getCover(),
                'class'        => 'block__image-img',
                'pictureClass' => 'game__card-miniature',
                'lazyLoad'     => true,
                'alt'          => $game->game->getTitle(),
                'retina'       => false,
                'breakpoints'  => [
                    -1 => 200,
                ],
            ])->render()?>
            <header class="game__card-header">
                <h2 class="game__name"><?=$game->game->getTitle()?></h2>
                <?php if ($releaseYear = $game->game->getReleaseYear()) : ?>
                    <span class="game__year"><?=$releaseYear?></span>
                <?php endif; ?>
            </header>
            <ul class="game__materials list--block">
                <?php foreach ($game->getMaterials() as $material) : ?>
                    <li class="game__materials-item">
                        <a
                            href="<?=$material->getMaterialUrl()?>"
                            class="game__material game__material--<?=$material->isFile() ? 'file' : 'article'?>"
                        >
                            <?php if ($material->isFile()) : ?>
                                <?=$this->getSvgContent('images/modules/Games/floppy.svg')?>
                            <?php else : ?>
                                <?=$this->getSvgContent('images/modules/Games/article.svg')?>
                            <?php endif; ?>
                            <h3 class="game__material-title"><?=$material->getShortTitle()?></h3>
                            <span class="game__material-description"><?=$material->getAnnotation()?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </article>
    </li>
<?php endif; ?>
