<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */
/** @var \BC\Widget\Head\Favicon $this */

$webPath = $this->getIconsWebPath();
?>
<link rel="icon" href="<?=$webPath?>/favicon.ico" />
<link rel="icon" href="<?=$webPath?>/favicon.svg" type="image/svg+xml" />
<link rel="apple-touch-icon" sizes="180x180" href="<?=$webPath?>/icon-180x180.png" />
<link rel="manifest" href="<?=$webPath?>/manifest.webmanifest" />