<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */

/** @var \BC\Widget\Common\Block\Gallery $this */

use BC\Widget\Common\Picture;

$slides = $this->getSlides();
?>
<section class="block__gallery<?php if ($this->isFullWidth()) : ?> block__gallery--full-width<?php endif; ?>">
    <ul class="block__gallery-scroller list--block">
        <?php foreach ($slides as $i => $slide) : ?>
            <li class="block__gallery-slide<?php if ($i === 0) : ?> block__gallery-slide--active<?php endif; ?>">
                <figure class="block__gallery-image">
                    <?php if ($this->isLightbox()) : ?>
                    <a
                        href="<?=$slide->getWebPath()?>"
                        class="lightbox"
                        data-pswp-width="<?=$slide->getWidth()?>"
                        data-pswp-height="<?=$slide->getHeight()?>"
                    >
                        <?php endif; ?>
                        <?=new Picture([
                            'image'        => $slide,
                            'class'        => null,
                            'pictureClass' => "block__gallery-picture",
                            'lazyLoad'     => $this->isLazy(),
                            'caption'      => $this->getCaption($i),
                            'breakpoints'  => [
                                470 => 500,
                                - 1 => 1000,
                            ],
                        ])->render()?>
                        <?php if ($this->isLightbox()) : ?>
                    </a>
                <?php endif; ?>
                    <?php if ($this->getCaption($i)) : ?>
                        <figcaption class="block__image-text"><?=$this->getCaption($i)?></figcaption>
                    <?php endif; ?>
                </figure>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="block__gallery-controls">
        <button class="icon-button block__gallery-btn block__gallery-btn--prev" tabindex="-1" disabled>
            <span class="visually-hidden">Назад</span>
            <?=$this->getSvgContent("images/icons/arrow-left.svg")?>
        </button>
        <div class="block__gallery-counter">
            <span class="block__gallery-counter-current">1</span>
            <span class="block__gallery-counter-divider">/</span>
            <span class="block__gallery-counter-total"><?=count($slides)?></span>
        </div>
        <button class="icon-button block__gallery-btn block__gallery-btn--next" tabindex="-1" disabled>
            <span class="visually-hidden">Вперед</span>
            <?=$this->getSvgContent("images/icons/arrow-right.svg")?>
        </button>
    </div>
</section>

