<?php

use BC\Widget\Common\Picture;

/** @noinspection PhpFullyQualifiedNameUsageInspection */
/** @var \BC\Widget\Common\Block\Media $this */
?>
<?php if ($this->isImage()) : ?>
    <figure class="block__image-figure">
        <?php if ($this->lightbox) : ?>
        <a
            href="<?=$this->media->getWebPath()?>"
            class="lightbox"
            data-pswp-width="<?=$this->media->getWidth()?>"
            data-pswp-height="<?=$this->media->getHeight()?>"
        >
            <?php endif; ?>
            <?=new Picture([
                'image'        => $this->media,
                'class'        => "block__image-img",
                'pictureClass' => "block__image-picture",
                'lazyLoad'     => $this->lazy,
                'caption'      => $this->caption,
                'breakpoints'  => [
                    470 => 500,
                    - 1 => 1000,
                ],
            ])->render()?>
            <?php if ($this->lightbox) : ?>
        </a>
    <?php endif; ?>
        <?php if ($this->caption) : ?>
            <figcaption class="block__image-text"><?=$this->caption?></figcaption>
        <?php endif; ?>
    </figure>
<?php elseif ($this->isVideo()) : ?>
    <?php
    $width = $this->media->getWidth();
    $height = $this->media->getHeight();
    ?>
    <figure class="block__image-figure figure--video<?php if ($this->lazy) : ?>  figure--video-lazy<?php endif; ?>">
        <video
            class="block__image-video"
            width="<?=$width?>"
            height="<?=$height?>"
            preload="<?=$this->lazy ? "none" : "auto"?>"
            autoplay
            muted
            loop
            playsinline
        >
            <source
                type="<?=$this->media->getMime()?>"
                width="<?=$width?>"
                height="<?=$height?>"
            <?=$this->lazy ? "data-src" : "src"?>="<?=$this->media->getWebPath()?>"
            />
        </video>
    </figure>
<?php endif; ?>
