<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */
/** @var \BC\Widget\Common\Block\TableOfContents $this */
?><details class="post__toc" open>
    <summary class="post__toc-summary">
        <span class="post__toc-label">Содержание</span>
        <span class="post__toc-icon">▼</span>
    </summary>
    <nav class="post__toc-nav">
        <ol class="post__toc-list">
            <?php foreach ($this->getItems() as $item) :?>
                <li class="post__toc-list-item">
                    <a href="#<?=($item['anchor'] ?? "")?>" class="post__toc-link"><?=($item['text'] ?? "")?></a>

                    <?php if (!empty($children = $this->getChildren($item))) :?>
                        <ol class="post__toc-sublist">
                            <?php foreach ($children as $child) :?>
                                <li class="post__toc-list-item">
                                    <a href="#<?=($child['anchor'] ?? "")?>" class="post__toc-link">
                                        <?=($child['text'] ?? "")?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ol>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </nav>
</details>
