services:
  BC\Modules\Games\Provider\MenuItemsProvider:
    decorates: BC\Provider\IMenuItemsProvider

  BC\Modules\Games\Provider\Admin\AppSettingsProvider:
    decorates: BC\Provider\Admin\IAppSettingsProvider

  BC\Modules\Games\Provider\CommentsProvider:
    decorates: BC\Provider\ICommentsProvider

  BC\Modules\Games\Provider\Admin\PageProvider:
    decorates: BC\Provider\Admin\IPageProvider

  BC\Modules\Games\Controller\Games: ~
