routes:
  index:
    path: /
    controller: BC\Controller\Index::run

  comment:
    path: /comment
    controller: BC\Controller\Comment::run

  admin:
    path: /admin/.*
    controller: BC\Controller\Admin::index

  admin_index:
    path: /admin
    controller: BC\Controller\Admin::index
