routes:
  index:
    path: /
    controller: BC\Controller\Index::run

  admin:
    path: /admin/.*
    controller: BC\Controller\Admin::index

  admin_index:
    path: /admin
    controller: BC\Controller\Admin::index
