services:
  BC\Core\Scanner\IWidgetClassScanner:
    class: BC\Core\Scanner\WidgetClassScanner

  BC\Core\Asset\Minifier\IMinifier:
    class: BC\Core\Asset\Minifier\MinifierFactory

  BC\Core\Asset\IAssetBuilder:
    class: BC\Core\Asset\AssetBuilder

  BC\Core\Config\IWebsiteSettings:
    class: BC\Core\Config\WebsiteSettings

  BC\Core\Media\Processor\ImageProcessorAvif:
    tags:
      - name: image.processor

  BC\Core\Media\Processor\ImageProcessorWebp:
    tags:
      - name: image.processor

  BC\Core\Media\PostProcessor\ImagePostprocessor:
    arguments:
      significantSizeDifferenceBytes: 1024
    tags:
      - name: image.postprocessor

  BC\Core\Media\IThumbnailGenerator:
    class: BC\Core\Media\ThumbnailGenerator

  BC\Core\Helper\IAttributesHelper:
    class: BC\Core\Helper\AttributesHelper

  BC\Core\Auth\IAuth:
    class: BC\Core\Auth\Auth

  BC\Core\Auth\ApiAuth:
    decorates: ApiPlatform\Core\Singleton\IAuth

  BC\Core\Converter\IConverter:
    class: BC\Core\Converter\ConverterFactory


# Website-specific services
  BC\Provider\IMenuItemsProvider:
    class: BC\Provider\MenuItemsProvider

  BC\Provider\IPulseItemsProvider:
    class: BC\Provider\PulseItemsProvider

  BC\Provider\IPathsProvider:
    class: BC\Provider\PathsProvider

  BC\Generator\IThumbnailsGenerator:
    class: BC\Generator\ThumbnailsGenerator


# Controllers
  BC\Controller\Index: ~
