<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */
/** @var \BC\Widget\Common\Header\Logo $this */
?>
<div class="header__column header__column--logo">
    <a href="<?=$this->getLogoUrl()?>" class="logo">
        <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64" fill="none">
            <rect x="4" y="4" width="24" height="24" rx="8" fill="currentColor" fill-opacity="0.2" />
            <rect x="36" y="4" width="24" height="24" rx="8" fill="currentColor" fill-opacity="0.2" />
            <rect x="4" y="36" width="24" height="24" rx="8" fill="currentColor" fill-opacity="0.2" />
            <rect x="36" y="36" width="24" height="24" rx="8" fill="#22c55e" />
        </svg>
    </a>
</div>
