<span class="header__mode-zone">
    <span class="header__mode-text">Тема: </span>

    <button class="icon-button icon-button--contrast header__nav-action-button header__nav-action-button--mode header__nav-action-button--mode-light header__nav-action-button--initializing">
        <span class="visually-hidden">Настройки темы</span>
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="header__nav-action-button-icon header__nav-action-button-icon--moon">
            <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
        </svg>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" class="header__nav-action-button-icon header__nav-action-button-icon--sun">
            <circle cx="12" cy="12" r="5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
            <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42" />
        </svg>
    </button>
</span>
