<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */

/** @var \BC\Modules\Blog\Widget\Note $this */

use BC\Widget\Blocks;

$note = $this->note;
?>
<article class="post note text-block">
    <header class="post__header">
        <?php if ($publishDate = $note->getPublishDate()) : ?>
            <time class="post__date" datetime="<?=$this->getDateTime($publishDate)?>">
                <?=$this->getHumanReadableDateTime($publishDate)?>
            </time>
        <?php endif; ?>
        <h1 class="post__title">
            <?php if (!$note->getPublished()) : ?>
                [Черновик]
            <?php endif; ?>
            <?=$note->getTitle()?>
        </h1>
    </header>
    <div class="post__body text-block">
        <?=new Blocks($note->getContent())->render()?>
    </div>
</article>
