<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */
/** @var \BC\Modules\Blog\Widget\Notes $this */
?>

<ul class="notes list--block">
    <?php foreach ($this->getNotes() as $note) : ?>
        <li class="note">
            <a href="<?=$note->getUrl()?>" class="note__link">
                <time
                    class="note__date"
                    datetime="<?=$this->getDateValue($note->getPublishDate())?>"
                >
                    <?=$this->getHumanReadableDate($note->getPublishDate())?>
                </time>
                <h2 class="note__title">
                    <?php if (!$note->getPublished()) : ?>
                        [Черновик]
                    <?php endif; ?>
                    <?=$note->getTitle()?>
                </h2>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
