<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */
/** @var \BC\Widget\Common\Content $this */

$page = $this->getPage();
$header = $page?->getHeader();
$description = $page?->getDescription();
$mainWidget = $page?->getMainWidget();
$backlink = $page?->getBackLink();
?>
<main class="content-area">
    <div class="<?=$page?->getContentContainerCssClass()?>">
        <?php if ($backlink): ?>
            <a href="<?=$backlink->url?>" class="back-link">
                <?=$this->getSvgContent('images/icons/back-arrow.svg')?>
                <?=$backlink->text?>
            </a>
        <?php endif; ?>
        <?php if ($header): ?>
            <h1><?=$header?></h1>
        <?php endif; ?>
        <?php if ($description): ?>
            <?php foreach ($description as $p) : ?>
                <p><?=$p?></p>
            <?php endforeach; ?>
        <?php endif; ?>
        <?=$mainWidget?->render(['page' => $page])?>
    </div>
</main>
