<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */
/** @var \BC\Widget\Common\Header $this */
?>
<header class="header">
    <div class="content-container header__container">
        <div class="header__column header__column--logo">
            <a href="<?=$this->getLogoUrl()?>" class="logo">
                <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64" fill="none">
                    <rect x="4" y="4" width="24" height="24" rx="8" fill="currentColor" fill-opacity="0.2" />
                    <rect x="36" y="4" width="24" height="24" rx="8" fill="currentColor" fill-opacity="0.2" />
                    <rect x="4" y="36" width="24" height="24" rx="8" fill="currentColor" fill-opacity="0.2" />
                    <rect x="36" y="36" width="24" height="24" rx="8" fill="#22c55e" />
                </svg>
            </a>
        </div>

        <div class="header__column header__column--menu-switcher">
            <button class="header__nav-action-button header__nav-action-button--menu button--link-like">
                <span class="visually-hidden">Меню сайта</span>
                <span class="burger-icon" aria-hidden="true">
            <span></span>
            <span></span>
        </span>
            </button>
        </div>

        <?=$this->renderWidgetList('header')?>
    </div>
</header>
