<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */
/** @var \BC\Widget\Sitemap $this */
?>
<?='<?xml version="1.0" encoding="UTF-8"?>'?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns:xhtml="http://www.w3.org/1999/xhtml">
    <?php foreach ($this->getSitemapPages() as $page): ?>
        <url>
            <loc><?=$this->buildFullPageUrl($page->url)?></loc>
            <changefreq><?=$page->changeFreq->value?></changefreq>
        </url>
    <?php endforeach; ?>
</urlset>
