services:
  BC\Modules\Games\Api\DataBuilder\Game\IGameDataBuilder:
    class: BC\Modules\Games\Api\DataBuilder\Game\GameDataBuilder

  BC\Modules\Games\Api\DataBuilder\GameMaterial\IGameMaterialDataBuilder:
    class: BC\Modules\Games\Api\DataBuilder\GameMaterial\GameMaterialDataBuilder
