services:
  BC\Modules\Blog\Core\Action\Post\ISavePostAction:
    class: BC\Modules\Blog\Core\Action\Post\SavePostAction

  BC\Modules\Blog\Core\Action\Post\ICreatePostAction:
    class: BC\Modules\Blog\Core\Action\Post\CreatePostAction

  BC\Modules\Blog\Core\Action\Post\IGetPostAction:
    class: BC\Modules\Blog\Core\Action\Post\GetPostAction

  BC\Modules\Blog\Core\Action\Validator\IPostValidator:
    class: BC\Modules\Blog\Core\Action\Validator\PostValidator

  BC\Modules\Blog\Core\Action\Tag\ICreateTagAction:
    class: BC\Modules\Blog\Core\Action\Tag\CreateTagAction

  BC\Modules\Blog\Core\Action\Tag\ISaveTagAction:
    class: BC\Modules\Blog\Core\Action\Tag\SaveTagAction

  BC\Modules\Blog\Core\Action\Note\ICreateNoteAction:
    class: BC\Modules\Blog\Core\Action\Note\CreateNoteAction

  BC\Modules\Blog\Core\Action\Note\ISaveNoteAction:
    class: BC\Modules\Blog\Core\Action\Note\SaveNoteAction

  BC\Modules\Blog\Core\Action\Note\IGetNoteAction:
    class: BC\Modules\Blog\Core\Action\Note\GetNoteAction

  BC\Modules\Blog\Core\Action\Validator\INoteValidator:
    class: BC\Modules\Blog\Core\Action\Validator\NoteValidator
