services:
  BC\Modules\Blog\Core\Action\Post\ISavePostAction:
    class: BC\Modules\Blog\Core\Action\Post\SavePostAction

  BC\Modules\Blog\Core\Action\Post\ICreatePostAction:
    class: BC\Modules\Blog\Core\Action\Post\CreatePostAction

  BC\Modules\Blog\Core\Action\Post\IGetPostAction:
    class: BC\Modules\Blog\Core\Action\Post\GetPostAction

  BC\Modules\Blog\Core\Action\Validator\IPostValidator:
    class: BC\Modules\Blog\Core\Action\Validator\PostValidator

  BC\Modules\Blog\Core\Action\Tag\ICreateTagAction:
    class: BC\Modules\Blog\Core\Action\Tag\CreateTagAction

  BC\Modules\Blog\Core\Action\Tag\ISaveTagAction:
    class: BC\Modules\Blog\Core\Action\Tag\SaveTagAction

