routes:
  posts_list:
    path: /blog
    controller: BC\Modules\Blog\Controller\Blog::renderPostList

  posts_list_page:
    path: /blog/page/{page}
    controller: BC\Modules\Blog\Controller\Blog::renderPostList

  posts_list_tag:
    path: /blog/tag/{tag}
    controller: BC\Modules\Blog\Controller\Blog::renderPostList

  posts_list_tag_page:
    path: /blog/tag/{tag}/page/{page}
    controller: BC\Modules\Blog\Controller\Blog::renderPostList

  # Тестовый роут: превью поста для соцсетей, рисуется на лету
  post_preview:
    path: /blog/preview/{id}
    controller: BC\Modules\Blog\Controller\Blog::renderPreview

  post:
    path: /blog/{slug}
    controller: BC\Modules\Blog\Controller\Blog::renderPost

services:
  BC\Modules\Blog\Controller\Blog: ~
