services:
  BC\Api\DataBuilder\Comment\ICommentDataBuilder:
    class: BC\Api\DataBuilder\Comment\CommentDataBuilder

  BC\Api\DataBuilder\Screenshot\IScreenshotDataBuilder:
    class: BC\Api\DataBuilder\Screenshot\ScreenshotDataBuilder

  BC\Api\DataBuilder\Photo\IPhotoDataBuilder:
    class: BC\Api\DataBuilder\Photo\PhotoDataBuilder

  BC\Api\DataBuilder\Media\IMediaDataBuilder:
    class: BC\Api\DataBuilder\Media\MediaDataBuilder

  BC\Api\DataBuilder\Redirect\IRedirectDataBuilder:
    class: BC\Api\DataBuilder\Redirect\RedirectDataBuilder

  BC\Api\DataBuilder\Fact\IFactDataBuilder:
    class: BC\Api\DataBuilder\Fact\FactDataBuilder

  BC\Api\DataBuilder\PhotoTag\IPhotoTagDataBuilder:
    class: BC\Api\DataBuilder\PhotoTag\PhotoTagDataBuilder

  BC\Api\DataBuilder\PulseItem\IPulseItemDataBuilder:
    class: BC\Api\DataBuilder\PulseItem\PulseItemDataBuilder
